FROM debian:rc-buggy

ENV DEBIAN_FRONTEND=noninteractive \
    GO_VERSION=1.22.0 \
    PATH=$PATH:/usr/local/go/bin:/root/.local/bin

RUN apt-get update && apt-get upgrade -y --no-install-recommends \
    && apt-get install -y --no-install-recommends apt-transport-https ca-certificates curl sudo gnupg \
    && apt-get install -y --no-install-recommends git make cmake gcc g++ python3 python3-pip python3-setuptools python3-wheel python3-dev zsh tmux \
    ninja-build unzip gettext software-properties-common silversearcher-ag fd-find shfmt \
    && rm -rf /var/lib/apt/lists/* && rm -rf /var/cache/apt/archives/* && rm -rf /tmp/*

## removed kubectl and hexctl per requirements

RUN curl -LO https://studygolang.com/dl/golang/go${GO_VERSION}.linux-amd64.tar.gz \
    && tar xvzf go${GO_VERSION}.linux-amd64.tar.gz -C /usr/local

## removed neovim and related configs per requirements

WORKDIR /root
