FROM tencentos/tencentos4-minimal:4.4-v20251020

ENV LV_BRANCH='release-1.3/neovim-0.9' \
    GO_VERSION=1.22.0 \
    PATH=$PATH:/usr/local/go/bin:/usr/local/nvim/bin:/root/.local/bin:/root/.local/bin

RUN yum update -y && yum upgrade -y \
    && yum install -y epel-release \
    && yum install -y curl sudo gnupg git \
    make cmake gcc gcc-c++ python3 python3-pip \
    python3-setuptools python3-wheel python3-devel zsh tmux \
    tar man xz gzip unzip \
    the_silver_searcher fd-find \
    && rm -rf /var/cache/yum

## removed kubectl and hexctl per requirements

RUN curl -LO https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz \
    && tar xvzf go${GO_VERSION}.linux-amd64.tar.gz -C /usr/local

WORKDIR /root
